#!/usr/bin/env python3
"""Replace Performance page 3-tabs with a flat scope+filter view (mirrors Targets page)."""
import os, sys
TARGET = r"C:\Users\KamalSAGUEM\OneDrive - Beyond believers\Bureau\Rehab app ( planner) - Copie\rigab_app\index.html"

def must_replace_once(src, anchor, replacement, label):
    n = src.count(anchor)
    if n == 0: raise SystemExit("[FAIL] anchor not found for " + label)
    if n > 1:  raise SystemExit("[FAIL] anchor appears " + str(n) + "x for " + label)
    return src.replace(anchor, replacement, 1)

def main():
    with open(TARGET, 'r', encoding='utf-8') as f:
        src = f.read()
    if "gmvRenderFlatPerformance" in src:
        print("[skip] already done"); return

    # ---- A: insert helpers before gmvRenderResults ----
    helpers = (
        "// ----- Performance flat view: rollup + render + wiring -----\n"
        "function gmvComputePerf(scope, filters) {\n"
        "  const fromMs = gmv.dateFrom ? new Date(gmv.dateFrom + 'T00:00:00').getTime() : -Infinity;\n"
        "  const toMs   = gmv.dateTo   ? new Date(gmv.dateTo   + 'T23:59:59').getTime() :  Infinity;\n"
        "  const sellersSet = new Set((filters && filters.sellers) || []);\n"
        "  const storesSet  = new Set((filters && filters.stores)  || []);\n"
        "  const clientsSet = new Set((filters && filters.clients) || []);\n"
        "  const catsSet    = new Set((filters && filters.categories) || []);\n"
        "  const rollup = {};\n"
        "  (gmv.orders || []).forEach(o => {\n"
        "    if (!o.phone || !gmv.clients[o.phone]) return;\n"
        "    if (!o.status || GMV_STATUSES.indexOf(o.status) < 0) return;\n"
        "    if (o.status !== 'PENDING') {\n"
        "      const t = o.date ? o.date.getTime() : 0;\n"
        "      if (t < fromMs || t > toMs) return;\n"
        "    }\n"
        "    const seller = gmv.clients[o.phone].seller || '(no seller)';\n"
        "    const store  = o.store || '(no store)';\n"
        "    const ent = (gmv.productCategories || {})[o.productCode || ''];\n"
        "    const category = (ent && ent.category) ? ent.category : '(uncategorized)';\n"
        "    if (sellersSet.size && !sellersSet.has(seller))   return;\n"
        "    if (storesSet.size  && !storesSet.has(store))     return;\n"
        "    if (clientsSet.size && !clientsSet.has(o.phone))  return;\n"
        "    if (catsSet.size    && !catsSet.has(category))    return;\n"
        "    let key, meta;\n"
        "    if (scope === 'sellers')        { key = seller; meta = { name: seller, seller: seller }; }\n"
        "    else if (scope === 'stores')    { key = store;  meta = { name: store,  store: store }; }\n"
        "    else if (scope === 'clients')   { key = o.phone; meta = { name: gmvDisplayName(o.phone), phone: o.phone, seller: seller }; }\n"
        "    else if (scope === 'categories'){ key = category; meta = { name: category, category: category }; }\n"
        "    else if (scope === 'seller-store')   { key = seller + '|' + store;       meta = { name: seller + ' \\u00d7 ' + store, seller: seller, store: store }; }\n"
        "    else if (scope === 'client-store')   { key = o.phone + '|' + store;      meta = { name: gmvDisplayName(o.phone) + ' \\u00d7 ' + store, phone: o.phone, store: store, seller: seller }; }\n"
        "    else if (scope === 'store-category') { key = store + '|' + category;     meta = { name: store + ' \\u00d7 ' + category, store: store, category: category }; }\n"
        "    else return;\n"
        "    if (!rollup[key]) rollup[key] = { meta: meta, status: {} };\n"
        "    rollup[key].status[o.status] = (rollup[key].status[o.status] || 0) + o.amount;\n"
        "  });\n"
        "  return rollup;\n"
        "}\n"
        "\n"
        "const GMV_PERF_SCOPES = [\n"
        "  { id: 'sellers',        label: 'Sellers' },\n"
        "  { id: 'stores',         label: 'Stores'  },\n"
        "  { id: 'clients',        label: 'Clients' },\n"
        "  { id: 'categories',     label: 'Categories' },\n"
        "  { id: 'seller-store',   label: 'Sellers \\u00d7 Stores' },\n"
        "  { id: 'client-store',   label: 'Clients \\u00d7 Stores' },\n"
        "  { id: 'store-category', label: 'Stores \\u00d7 Categories' }\n"
        "];\n"
        "\n"
        "function gmvRenderFlatPerformance(wrap) {\n"
        "  if (!gmv.perfFilters) gmv.perfFilters = { sellers: [], stores: [], clients: [], categories: [], search: '' };\n"
        "  if (!gmv.perfScope)   {\n"
        "    try { gmv.perfScope = loadJSON('rihab_gmv_perfscope_v1') || 'sellers'; } catch (_) { gmv.perfScope = 'sellers'; }\n"
        "  }\n"
        "  if (!gmv.perfLimit)   gmv.perfLimit = 50;\n"
        "  const scope = gmv.perfScope;\n"
        "  const filters = gmv.perfFilters;\n"
        "  const rollup = gmvComputePerf(scope, filters);\n"
        "  let rows = Object.values(rollup);\n"
        "  const q = (filters.search || '').trim().toLowerCase();\n"
        "  if (q) rows = rows.filter(r => (r.meta.name || '').toLowerCase().includes(q));\n"
        "  rows.sort((a, b) => ((b.status['DELIVERED']||0) - (a.status['DELIVERED']||0)) || (a.meta.name||'').localeCompare(b.meta.name||''));\n"
        "  const scopeOpts = GMV_PERF_SCOPES.map(o => '<option value=\"' + o.id + '\"' + (o.id === scope ? ' selected' : '') + '>' + escapeHtml(o.label) + '</option>').join('');\n"
        "  const chip = (kind, label) => {\n"
        "    const n = (filters[kind] || []).length;\n"
        "    return '<button type=\"button\" class=\"gmv-flt-chip' + (n ? ' has-selection' : '') + '\" data-perf-flt-kind=\"' + kind + '\">' +\n"
        "      '<span>' + label + '</span>' +\n"
        "      (n ? '<span class=\"chip-count\">' + n + '</span>' : '<span style=\"color:var(--text-soft);font-size:11px;\">All</span>') +\n"
        "    '</button>';\n"
        "  };\n"
        "  const hasAny = (filters.sellers||[]).length || (filters.stores||[]).length || (filters.clients||[]).length || (filters.categories||[]).length || (filters.search && filters.search.trim());\n"
        "  let html = '<div class=\"gmv-flt-bar\">' +\n"
        "    '<select class=\"gmv-flt-scope\" id=\"gmvPerfScope\">' + scopeOpts + '</select>' +\n"
        "    '<input type=\"text\" class=\"gmv-flt-search\" id=\"gmvPerfSearch\" placeholder=\"Search...\" value=\"' + escapeHtml(filters.search || '') + '\">' +\n"
        "    chip('sellers', 'Sellers') + chip('stores', 'Stores') + chip('clients', 'Clients') + chip('categories', 'Categories') +\n"
        "    (hasAny ? '<button type=\"button\" class=\"gmv-flt-clear\" id=\"gmvPerfClear\">\\u2715 Clear filters</button>' : '') +\n"
        "    '<span class=\"gmv-flt-count\">' + rows.length + ' rows</span>' +\n"
        "  '</div>';\n"
        "  if (!rows.length) {\n"
        "    html += '<div class=\"gmv-empty\"><div class=\"gmv-empty-icon\">\\u26A0</div>No data matches your filters.</div>';\n"
        "    wrap.innerHTML = html;\n"
        "    gmvWireFlatPerfHandlers(wrap);\n"
        "    return;\n"
        "  }\n"
        "  const limit = gmv.perfLimit || 50;\n"
        "  const visible = rows.slice(0, limit);\n"
        "  const hidden = Math.max(0, rows.length - visible.length);\n"
        "  const bucket = gmvActivePeriodBucket();\n"
        "  const targetForRow = (m) => {\n"
        "    if (scope === 'sellers')        return bucket.sellers[m.seller] || 0;\n"
        "    if (scope === 'stores')         return bucket.stores[m.store] || 0;\n"
        "    if (scope === 'clients')        return bucket.clients[m.phone] || 0;\n"
        "    if (scope === 'categories')     return (bucket.categories || {})[m.category] || 0;\n"
        "    if (scope === 'seller-store')   return ((bucket.storesBySeller || {})[m.seller] || {})[m.store] || 0;\n"
        "    if (scope === 'client-store')   return ((bucket.storesByClient || {})[m.phone] || {})[m.store] || 0;\n"
        "    if (scope === 'store-category') return ((bucket.categoriesByStore || {})[m.store] || {})[m.category] || 0;\n"
        "    return 0;\n"
        "  };\n"
        "  let table = '<div class=\"gmv-table-wrap\"><table class=\"gmv-table\"><thead><tr>';\n"
        "  if (scope === 'sellers')              table += '<th>Seller</th>';\n"
        "  else if (scope === 'stores')          table += '<th>Store</th>';\n"
        "  else if (scope === 'clients')         table += '<th>Client</th>';\n"
        "  else if (scope === 'categories')      table += '<th>Category</th>';\n"
        "  else if (scope === 'seller-store')    table += '<th>Seller</th><th>Store</th>';\n"
        "  else if (scope === 'client-store')    table += '<th>Client</th><th>Store</th>';\n"
        "  else if (scope === 'store-category')  table += '<th>Store</th><th>Category</th>';\n"
        "  table += '<th class=\"num\">Delivered</th><th class=\"num\">Target</th><th>Progress</th><th class=\"num\" style=\"width:54px;\">%</th>';\n"
        "  GMV_STATUSES.filter(s => s !== 'DELIVERED').forEach(s => {\n"
        "    const lbl = s.replace(/_/g, ' ').toLowerCase().replace(/\\b\\w/g, c => c.toUpperCase());\n"
        "    table += '<th class=\"num\" title=\"' + s + '\">' + lbl + '</th>';\n"
        "  });\n"
        "  table += '</tr></thead><tbody>';\n"
        "  let totDelivered = 0, totTarget = 0;\n"
        "  const totByStatus = {};\n"
        "  visible.forEach(r => {\n"
        "    const m = r.meta;\n"
        "    const delivered = r.status['DELIVERED'] || 0;\n"
        "    const target = targetForRow(m);\n"
        "    totDelivered += delivered; totTarget += target;\n"
        "    let bulletHtml, pctTxt;\n"
        "    if (target > 0) {\n"
        "      const scaleMax = target / 0.75;\n"
        "      const fillPct = Math.max(0, Math.min(100, (delivered / scaleMax) * 100));\n"
        "      const ok = delivered >= target;\n"
        "      bulletHtml = '<div class=\"gmv-bullet\" title=\"' + gmvFmtFull(delivered) + ' / ' + gmvFmtFull(target) + ' MAD\">' +\n"
        "        '<div class=\"gmv-bullet-fill ' + (ok ? 'ok' : 'partial') + '\" style=\"width:' + fillPct + '%;\"></div>' +\n"
        "        '<div class=\"gmv-bullet-tick\" style=\"left:75%;\"></div>' +\n"
        "      '</div>';\n"
        "      pctTxt = Math.round((delivered / target) * 100) + '%';\n"
        "    } else {\n"
        "      bulletHtml = '<span style=\"font-size:11px; color:var(--text-soft);\">no target</span>';\n"
        "      pctTxt = '<span class=\"muted-num\">0%</span>';\n"
        "    }\n"
        "    table += '<tr class=\"gmv-row-seller\">';\n"
        "    if (scope === 'sellers')              table += '<td><div class=\"gmv-seller-name\">' + escapeHtml(m.name) + '</div></td>';\n"
        "    else if (scope === 'stores')          table += '<td><div class=\"gmv-seller-name\">' + escapeHtml(m.name) + '</div></td>';\n"
        "    else if (scope === 'clients')         table += '<td><div class=\"gmv-seller-name\">' + escapeHtml(m.name) + '</div><div class=\"gmv-seller-meta\">' + escapeHtml(m.seller || '') + ' \\u00b7 ' + escapeHtml(m.phone) + '</div></td>';\n"
        "    else if (scope === 'categories')      table += '<td><div class=\"gmv-seller-name\">' + escapeHtml(m.name) + '</div></td>';\n"
        "    else if (scope === 'seller-store')    table += '<td><div class=\"gmv-seller-name\">' + escapeHtml(m.seller) + '</div></td><td>' + escapeHtml(m.store) + '</td>';\n"
        "    else if (scope === 'client-store')    table += '<td><div class=\"gmv-seller-name\">' + escapeHtml(gmvDisplayName(m.phone)) + '</div><div class=\"gmv-seller-meta\">' + escapeHtml(m.seller || '') + ' \\u00b7 ' + escapeHtml(m.phone) + '</div></td><td>' + escapeHtml(m.store) + '</td>';\n"
        "    else if (scope === 'store-category')  table += '<td><div class=\"gmv-seller-name\">' + escapeHtml(m.store) + '</div></td><td>' + escapeHtml(m.category) + '</td>';\n"
        "    table += '<td class=\"num\" title=\"' + gmvFmtFull(delivered) + ' MAD\">' + gmvFmtCompact(delivered) + '</td>';\n"
        "    table += '<td class=\"num' + (target > 0 ? '' : ' muted-num') + '\">' + (target > 0 ? gmvFmtCompact(target) : '0') + '</td>';\n"
        "    table += '<td>' + bulletHtml + '</td>';\n"
        "    table += '<td class=\"num\">' + pctTxt + '</td>';\n"
        "    GMV_STATUSES.filter(s => s !== 'DELIVERED').forEach(s => {\n"
        "      const v = r.status[s] || 0;\n"
        "      totByStatus[s] = (totByStatus[s] || 0) + v;\n"
        "      table += '<td class=\"num' + (v > 0 ? '' : ' muted-num') + '\" title=\"' + gmvFmtFull(v) + ' MAD\">' + (v > 0 ? gmvFmtCompact(v) : '0') + '</td>';\n"
        "    });\n"
        "    table += '</tr>';\n"
        "  });\n"
        "  const colCount = (scope === 'seller-store' || scope === 'client-store' || scope === 'store-category') ? 6 + GMV_STATUSES.length - 1 : 5 + GMV_STATUSES.length - 1;\n"
        "  table += '</tbody>';\n"
        "  if (hidden > 0) {\n"
        "    table += '<tfoot><tr><td colspan=\"' + colCount + '\"><button type=\"button\" class=\"gmv-showmore-btn\" id=\"gmvPerfShowMore\">Show more <span class=\"gmv-showmore-count\">+' + Math.min(50, hidden) + ' (' + hidden + ' hidden)</span></button></td></tr></tfoot>';\n"
        "  }\n"
        "  table += '</table></div>';\n"
        "  html += table;\n"
        "  wrap.innerHTML = html;\n"
        "  gmvWireFlatPerfHandlers(wrap);\n"
        "}\n"
        "\n"
        "function gmvWireFlatPerfHandlers(wrap) {\n"
        "  const sel = wrap.querySelector('#gmvPerfScope');\n"
        "  if (sel) sel.addEventListener('change', () => {\n"
        "    gmv.perfScope = sel.value; gmv.perfLimit = 50;\n"
        "    try { saveJSON('rihab_gmv_perfscope_v1', gmv.perfScope); } catch (_) {}\n"
        "    gmvRenderResults();\n"
        "  });\n"
        "  const srch = wrap.querySelector('#gmvPerfSearch');\n"
        "  if (srch) {\n"
        "    let t = null;\n"
        "    srch.addEventListener('input', () => {\n"
        "      gmv.perfFilters.search = srch.value || '';\n"
        "      const caret = srch.selectionStart;\n"
        "      clearTimeout(t);\n"
        "      t = setTimeout(() => {\n"
        "        gmvRenderResults();\n"
        "        const next = document.getElementById('gmvPerfSearch');\n"
        "        if (next) { next.focus(); try { next.setSelectionRange(caret, caret); } catch(_){} }\n"
        "      }, 100);\n"
        "    });\n"
        "  }\n"
        "  wrap.querySelectorAll('button[data-perf-flt-kind]').forEach(btn => {\n"
        "    btn.addEventListener('click', e => {\n"
        "      e.stopPropagation();\n"
        "      gmvOpenPerfFltPopover(btn, btn.dataset.perfFltKind);\n"
        "    });\n"
        "  });\n"
        "  const clr = wrap.querySelector('#gmvPerfClear');\n"
        "  if (clr) clr.addEventListener('click', () => {\n"
        "    gmv.perfFilters = { sellers: [], stores: [], clients: [], categories: [], search: '' };\n"
        "    gmvRenderResults();\n"
        "  });\n"
        "  const more = wrap.querySelector('#gmvPerfShowMore');\n"
        "  if (more) more.addEventListener('click', () => {\n"
        "    gmv.perfLimit = (gmv.perfLimit || 50) + 50;\n"
        "    gmvRenderResults();\n"
        "  });\n"
        "}\n"
        "\n"
        "function gmvOpenPerfFltPopover(chip, kind) {\n"
        "  gmvCloseFltPopover();\n"
        "  const filters = gmv.perfFilters;\n"
        "  const selected = new Set(filters[kind] || []);\n"
        "  let options = [];\n"
        "  if (kind === 'sellers') options = gmvUniqueSellers();\n"
        "  else if (kind === 'stores')  options = gmvAllStores();\n"
        "  else if (kind === 'categories') options = gmvAllCategories();\n"
        "  else if (kind === 'clients') options = Object.keys(gmv.clients || {}).sort((a,b)=> gmvDisplayName(a).localeCompare(gmvDisplayName(b)));\n"
        "  const labelOf = (k, v) => k === 'clients' ? gmvDisplayName(v) : v;\n"
        "  const pop = document.createElement('div');\n"
        "  pop.className = 'gmv-flt-popover open';\n"
        "  pop.innerHTML = '<div class=\"gmv-flt-popover-head\">' + escapeHtml(kind) + '</div>' +\n"
        "    options.map(o => '<label class=\"gmv-flt-opt\"><input type=\"checkbox\" value=\"' + escapeHtml(o) + '\"' + (selected.has(o) ? ' checked' : '') + '> <span>' + escapeHtml(labelOf(kind, o)) + '</span></label>').join('') +\n"
        "    '<div class=\"gmv-flt-popover-foot\"><button type=\"button\" class=\"gmv-flt-popover-close\">Apply</button></div>';\n"
        "  document.body.appendChild(pop);\n"
        "  const r = chip.getBoundingClientRect();\n"
        "  pop.style.position = 'fixed'; pop.style.left = r.left + 'px'; pop.style.top = (r.bottom + 4) + 'px'; pop.style.zIndex = '99';\n"
        "  _gmvFltOpen = pop;\n"
        "  pop.querySelectorAll('input[type=\"checkbox\"]').forEach(cb => {\n"
        "    cb.addEventListener('change', () => {\n"
        "      const v = cb.value;\n"
        "      const arr = filters[kind] || (filters[kind] = []);\n"
        "      if (cb.checked) { if (!arr.includes(v)) arr.push(v); }\n"
        "      else { const i = arr.indexOf(v); if (i >= 0) arr.splice(i, 1); }\n"
        "      gmvRenderResults();\n"
        "    });\n"
        "  });\n"
        "  const closeBtn = pop.querySelector('.gmv-flt-popover-close');\n"
        "  if (closeBtn) closeBtn.addEventListener('click', () => gmvCloseFltPopover());\n"
        "  setTimeout(() => {\n"
        "    const handler = (ev) => {\n"
        "      if (!pop.contains(ev.target) && !chip.contains(ev.target)) {\n"
        "        gmvCloseFltPopover();\n"
        "        document.removeEventListener('mousedown', handler, true);\n"
        "      }\n"
        "    };\n"
        "    document.addEventListener('mousedown', handler, true);\n"
        "  }, 0);\n"
        "}\n"
        "\n"
    )
    src = must_replace_once(src, "function gmvRenderResults() {", helpers + "function gmvRenderResults() {", "A: helpers")

    # ---- B: in gmvRenderResults, when page === 'performance' route to flat perf and return early ----
    # Anchor: the data-empty check at the top of gmvRenderResults
    old_b = (
        "  const result = gmvComputeReached();\n"
        "  if (page === 'performance') {\n"
        "    gmvRenderHero(result);\n"
        "    gmvRenderMiniStrip(result);\n"
        "  }"
    )
    new_b = (
        "  const result = gmvComputeReached();\n"
        "  if (page === 'performance') {\n"
        "    gmvRenderHero(result);\n"
        "    gmvRenderMiniStrip(result);\n"
        "    gmvRenderFlatPerformance(wrap);\n"
        "    return;\n"
        "  }"
    )
    src = must_replace_once(src, old_b, new_b, "B: route to flat perf")

    with open(TARGET, 'w', encoding='utf-8') as f:
        f.write(src)
    print("[OK] Performance page now has scope dropdown + filters (Sellers/Stores/Clients/Categories + crosses).")

if __name__ == '__main__':
    main()
